### ISSUE TITLE
Master do file and failure to execute called do files + line vs. selection output

### ISSUE THREAD

**Issue by taylorjwright** [kylebarron/stata_kernel#244] opened 2018-11-22 16:09 UTC
I'm using Atom 1.32.1 and either Ubuntu 16.04 or macOS High Sierra 10.13.6. 

When I include several do files inside my master do file and attempt to execute the master do file, only the first few do files execute. The indicator in the bottom of Atom tells me that Stata is idle despite the fact that there should be more do files to execute. Opening each do file and running the code inside works fine, as does running the master do file in an instance of Stata directly.

In a perhaps related note, the first do file displays the log close and data signature set output that concludes the file while the second do file (after which the subsequent do files contained in the master do file do not run) does not, despite containing the same ending lines of code.

Everything seems to work best when I run code line-by-line but selecting a section of code and running it often results in less informative output (some output that is displayed when run line-by-line does not seem to be displayed when part of a larger selection of code that is executed). 

Keep up the great work. Building and maintaining this can't be easy!

**Comment by kylebarron** [comment] 2018-11-22 16:16
Can you give a [reproducible example](https://stackoverflow.com/help/mcve)?

I can't reproduce this:
![image](https://user-images.githubusercontent.com/15164633/48913918-dfd27300-ee47-11e8-90cf-a43068725c05.png)

**Comment by taylorjwright** [comment] 2018-12-04 15:17
Sorry, I meant to come up with an example but I haven't had a chance yet. 

After going through some log files it appears that I'm experiencing a break during my compress command followed by an invalid command error (seemingly trying to interpret the file's datasignature as a command). I'm not sure this is an issue on your end though it is puzzling that things seem to work fine on Stata itself.

Hopefully I'll find a bit of time to come up with a reproducible example in the next little while.

**Comment by kylebarron** [comment] 2019-01-17 14:52
I'm closing for now, but feel free to reopen if you find an example

**Closed by kylebarron** 2019-01-17 14:52 UTC
