### ISSUE TITLE
Graph display bug after setting user _graph_keywords?

### ISSUE THREAD

**Issue by zdlspace0528** [kylebarron/stata_kernel#415] opened 2022-03-31 20:45 UTC
I use Stata 17.0 MP2 on MacBook Air M1.I have install stata-kernel by 

[code]
pip install git+https://github.com/mcaceresb/stata_kernel.git@dev-stata17-graph-fix
[/code]

I have set 
[code]
user_graph_keywords = coefplot,sepscatter
[/code]

but when I run

[code]
sysuse auto,clear
sepscatter price mpg,sep(foreign)
[/code]

it does not display the graph.

Any help will be appreciated.

Best
Raymond

**Comment by mcaceresb** [comment] 2022-03-31 20:57
@zdlspace0528 This is a known issue and I hadn't gotten around to fixing it mainly because I didn't have access to Stata 17. This has changed recently, so thank you for reminding me of the issue.

There's been a PRs open for it for almost a year in #394; I'm looking it over and it seems fairly straightforward. I'll probably get to testing it out/merging it before weekend. However, feel free to try it in the meantime and see if it helps.

**Comment by zdlspace0528** [comment] 2022-03-31 21:10
@mcaceresb I have tried the PRs in #394.But it seems that setting user_graph_keywords does not work either.

**Comment by mcaceresb** [comment] 2022-03-31 21:12
@zdlspace0528 Mmm. I see. Thank you for letting me know. Just to confirm: You tried the PR and no graphs were displayed _from the PR branch_? Even after running e.g. `graph display`?

**Comment by zdlspace0528** [comment] 2022-03-31 21:24
<img width="836" alt="image" src="https://user-images.githubusercontent.com/75175622/161151671-a5c0b313-5350-4a43-b1a7-22ff1ed7d857.png">

**Comment by zdlspace0528** [comment] 2022-04-01 21:18
I mean that we can see the variables window in jupyter notebook just like Stata’s variables window.


| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/2/2022 03:25，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 Are you looking for %head and %tail magics?

**Comment by mcaceresb** [comment] 2022-04-01 21:26
@zdlspace0528 AFAIK the kernel doesn't have that functionality. You can always type `desc`/`ds`/etc to see the variables in memory.

**Comment by zdlspace0528** [comment] 2022-04-01 21:42
I see.Thank you.


I have another question. I find the Stata command browse is unrecognized.




| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/2/2022 03:25，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 Are you looking for %head and %tail magics?

**Comment by mcaceresb** [comment] 2022-04-01 22:05
@zdlspace0528 `browse` is specific to the Stata GUI.

**Comment by zdlspace0528** [comment] 2022-04-04 03:33
Dear Mauricio，
I find that you have updated the stata-kernel.
How can I update to the lastest version.
Can you show me the code to update it?


| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/2/2022 03:25，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 Are you looking for %head and %tail magics?

**Comment by zdlspace0528** [comment] 2022-04-04 03:34
Can I update it by typing "pip install ***@***.***” ?


| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/2/2022 03:25，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 Are you looking for %head and %tail magics?

**Comment by zdlspace0528** [comment] 2022-04-04 03:36
Can I update it by typing "pip install git+https://github.com/mcaceresb/stata_kernel.git@dev-stata17-graph-fix” ?

**Comment by mcaceresb** [comment] 2022-04-04 04:36
@zdlspace0528 I think if you uninstall and reinstall from this repo it will work. The changes should be in master (simple upgrade might not do bc I forgot to bump the version, so uninstall and reinstall is the way to go).

**Comment by zdlspace0528** [comment] 2022-04-04 04:49
Does the update solve the problem of graph display binscattter?If I add the binscatter into the user-key-words, can it automatically display the binscatter graph?


| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/1/2022 04:58，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 This is a known issue and I hadn't gotten around to fixing it mainly because I didn't have access to Stata 17. This has changed recently, so thank you for reminding me of the issue.

There's been a PRs open for it for almost a year in #394; I'm looking it over and it seems fairly straightforward. I'll probably get to testing it out/merging it before weekend. However, feel free to try it in the meantime and see if it helps.

**Comment by zdlspace0528** [comment] 2022-04-04 04:56
I wonder if I can update it by typing the codes below?


pip uninstall stata-kernel
pip install ***@***.***


Best,
Raymond
| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/4/2022 12:36，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 I think if you uninstall and reinstall from this repo it will work. The changes should be in master (simple upgrade might not do bc I forgot to bump the version, so uninstall and reinstall is the way to go).

**Comment by mcaceresb** [comment] 2022-04-04 05:15
@zdlspace0528 Your code is censored so I don't know. Probably, but it's hard to say bc parts of your code get replace with asterisks.

**Comment by zdlspace0528** [comment] 2022-04-04 05:19
pip uninstall stata-kernel
pip install git+https://github.com/kylebarron/stata_kernel.git@master

Best,
Raymond

**Comment by mcaceresb** [comment] 2022-04-04 05:51
I think it's `stata_kernel`; also, I think you need to run `python -m stata_kernel.install` after, as the docs note.

**Comment by zdlspace0528** [comment] 2022-04-04 05:55
Thanks a lot.
Does the update solve the problem of graph display binscattter?If I add the binscatter into the user-key-words, can it automatically display the binscatter graph?

**Comment by mcaceresb** [comment] 2022-04-04 11:50
@zdlspace0528 Kt should

**Comment by mcaceresb** [comment] 2022-04-04 14:55
Can you post the relevant code snippet and attach your log file? I can't reproduce this issue.

**Comment by zdlspace0528** [comment] 2022-04-04 15:17
<img width="966" alt="截屏2022-04-04 23 11 52" src="https://user-images.githubusercontent.com/75175622/161575250-554b6c7a-0ade-43aa-8611-42b0042f4742.png">
Firstly, it seems that the I can not use _log_ in jupyter.

Secondly, it is going round and round, but can not get result when I plot the graph.
<img width="963" alt="截屏2022-04-04 23 13 11" src="https://user-images.githubusercontent.com/75175622/161575949-cd369432-5e6e-49b0-91a9-29331996ed2b.png">

**Comment by mcaceresb** [comment] 2022-04-04 18:04
@zdlspace0528 I see what you mean; I think I fixed in in #422. Should merge soon.

**Closed** 2022-04-04 18:29 UTC

**Comment by zdlspace0528** [comment] 2022-04-04 19:42
Thanks very much.You solve all my problem.
<img width="1080" alt="截屏2022-04-05 03 41 48" src="https://user-images.githubusercontent.com/75175622/161619673-2a11cc0b-f785-47da-b285-e11752ae0485.png">

**Comment by zdlspace0528** [comment] 2022-04-04 19:45
In the future,If you add Stata variables window in the jupyter , just like python's variables window. It will be more perfect.

**Comment by zdlspace0528** [comment] 2022-04-04 21:41
Dear @mcaceresb ,
Now there is another problem.When I run xtdidregress ,which is a new official command of Stata 17,it can not display the trendplot graph,even use the _graph display_.
<img width="866" alt="截屏2022-04-05 05 38 54" src="https://user-images.githubusercontent.com/75175622/161636893-ac5ae8c6-23e2-4012-9ae5-880287b9b384.png">

**Comment by mcaceresb** [comment] 2022-04-04 21:53
@zdlspace0528 Try `set more off`

**Comment by zdlspace0528** [comment] 2022-04-04 22:04
Yes，I just set more off,and it works well.Thanks.
| |
张德亮
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/5/2022 05:53，Mauricio Caceres ***@***.***> wrote：

@zdlspace0528 Try set more off

**Comment by zdlspace0528** [comment] 2022-04-05 01:15
Dear @mcaceresb ,
I have another problem , I run the **synth** command,
<img width="969" alt="截屏2022-04-05 09 10 12" src="https://user-images.githubusercontent.com/75175622/161658439-546e31c3-bb9a-4ef5-9114-83a6bf5bc3dd.png">

I can run the codes successfully in Stata.But should use Rosseta to open Stata. I wonder How can stata-kernel choose Rosseta when run codes in jupyter?

<img width="638" alt="截屏2022-04-05 09 12 59" src="https://user-images.githubusercontent.com/75175622/161658585-1e651634-f54a-4fad-9fa2-7d643644fb75.png">

**Comment by mcaceresb** [comment] 2022-04-05 01:56
@zdlspace0528 I don't know what Rosseta is, and I also don't know how you got Stata to use it. One thing you can try is `cd` into ado/plus/s and see if the kernel still fails.

Btw I was able to install the `synth` package and run the test code on the kernel without issue, so I am not sure why the plugin would fail to load in your case in the kernel but not on a regular Stata session. 

I hope you find a solution; please understand it's hard to provide package-specific help, specially when there are plugins involved and the issue is likely to be platform-specific.
