### ISSUE TITLE
getting rid of red box when making your stata code a webpage via jupyter

### ISSUE THREAD

**Issue by jeremyfreese** [kylebarron/stata_kernel#164] opened 2018-09-12 16:48 UTC
First off, this kernel is *great*.  When I teach, I would love to be able to use Jupyter to be able to easily make handsome webpages that show students how to do different things.

One problem I've run into is shown by the example I've posted here:
http://www.boydetective.net/docs/All_lowercase.html

Looks good except for the annoying red box that immediately draws the eye and conveys that something is amiss.  I'm presuming it has to do with the `"` '"' construction and how that would be not be kosher in Python.  Is eliminating that red box something that would be easy, or hard?

**Comment by kylebarron** [comment] 2018-09-12 17:55
Ah. This is actually a bug with the code that the underlying syntax highlighter, Pygments, uses to highlight Stata code, and not specifically an issue with this kernel. @mcaceresb originally wrote that; I've been meaning to update it, but haven't gotten around to it yet, and hadn't been aware of any actual errors like this.

It's pretty easy to fix this. Should be able to within a few days.

Note for me and @mcaceresb:

To reproduce, create a file `test.do` with the contents ``` `"`r(levels)'"' ``` then run
```
pygmentize -O full -f html -l stata -o test.html test.do
```

The red box here
![image](https://user-images.githubusercontent.com/15164633/45442874-375aa280-b691-11e8-8894-b94048aee664.png)
in HTML has class `err`:
```html
<span class="err">r(levels)</span>
```

In the Stata pygments lexer [source](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/stata.py), the flow goes like this:

- See `` `" ``, enter `vars-strings` and then add `String` scope and enter into `string_mquote`. 
- Inside `string_mquote`, it then matches `` ` ``, which adds scope `Name.Variable` and enters into `var_validlocal`.
- Inside `var_validlocal`, the only rule is `\w{0,31}`. But locals can include many more characters, such as `(`. Since there is no fallback option, this produces an error in Pygments.

**Comment by kylebarron** [comment] 2018-09-12 18:04
@mcaceresb am I correct in noting that there has been [no activity](https://bitbucket.org/birkenfeld/pygments-main/commits/branch/default) in the Pygments repository for 18 months?

For something like this or Codemirror syntax highlighting, I may add highlighting files to this repository, and then as part of starting the kernel, check if the files at
```py
from pkg_resources import resource_filename
resource_filename('pygments', 'lexers/stata.py')
```

are current, and if not, replace them.

**Comment by mcaceresb** [comment] 2018-09-12 18:13
[This says](https://bitbucket.org/birkenfeld/pygments-main) there was movement in the past month.

At any rate, yes, I ought to path that...

**Comment by kylebarron** [comment] 2018-09-12 18:29
But I have no idea how bitbucket arrives at that date... All of the branches date back at least to March 2017:
https://bitbucket.org/birkenfeld/pygments-main/branches/

**Comment by mcaceresb** [comment] 2018-09-12 18:52
> * Inside `var_validlocal`, the only rule is `\w{0,31}`. But locals can include many more characters, such as `(`. Since there is no fallback option, this produces an error in Pygments.

Interesting. Per our prior discussions almost anything can be in a local, though. I reckon I ought to just copy the rules you implemented in your repo, no?

**Comment by kylebarron** [comment] 2018-09-12 19:18
`language-stata` isn't perfectly translatable to Pygments. There are parts that don't make sense to add, and the structure of the syntax file is somewhat different. Do you want me to make a PR to your `highlight-sas-stata` repo?

**Comment by mcaceresb** [comment] 2018-09-13 01:53
Any thoughts on how to handle nested globals? Since I'm highlighting everything for locals this is fine, but globals need not have the `{}` as delimiters and everything after 32 characters seems to get ignored.

**Comment by kylebarron** [comment] 2018-09-13 02:03
Can you have nested globals if you don't use `${}`?

**Comment by mcaceresb** [comment] 2018-09-13 02:05
Interesting. I guess not.

**Comment by mcaceresb** [comment] 2018-09-13 02:06
But even `{}` fails if the global is too long...

**Comment by jeremyfreese** [comment] 2018-09-13 02:07
(Global names are limited to 32 characters in Stata, no matter how they are named; local names to 31.)

**Comment by kylebarron** [comment] 2018-09-13 02:10
> But even {} fails if the global is too long...

Sure, but I don't necessarily think it's important for this syntax highlighter to be exact in this way. If we color a 35-character word as a global, when they run it in Stata they'll discover it's too long

**Comment by mcaceresb** [comment] 2018-09-13 02:12
@jeremyfreese The issue is that Stata evaluates things in `${}` and ```'`` other than global and local variable _names_. For instance, it evaluates locals inside `${}`, and it evaluates all sorts of things inside ```'``. We had a field day figuring out corner cases [here](https://github.com/kylebarron/language-stata/issues/90), which started with trying to figure out comment parsing rules. 

For instance:
```stata
local i 1
disp "i = `i++Locals here are evaluated. `++i', `++i', and `i++' are evaluated.'"

local i = 1
disp `i"/*`++i'*/"Does this print 1, 2, 3? /*"`++i'"*/'
```

For nested globals, name length only applies to the final evaluation, so this is valid:
```stata
global HelloThisIsAVeryLengthyGlobalYes 23
local RandomLocalAlsoVeryLongName ThisIsAVeryLengthyGlobal
disp "${Hello`RandomLocalAlsoVeryLongName'Yes}"
```

**Comment by mcaceresb** [comment] 2018-09-13 02:14
> Sure, but I don't necessarily think it's important for this syntax highlighter to be exact in this way. If we color a 35-character word as a global, when they run it in Stata they'll discover it's too long

Sure.

**Comment by mcaceresb** [comment] 2018-09-13 21:06
Btw this is fixed in the Stata lexer [here](https://github.com/mcaceresb/highlight-sas-stata). You can replace the old pygments lexer on your system with `pygments/pygments/lexers/stata.py` on that repo. 

I'll submit a PR but, as noted, that might take a while to make it upstream. @kylebarron Not sure if you can replace the lexer during the install?

**Comment by kylebarron** [comment] 2018-09-14 03:13
@jeremyfreese (and @mcaceresb)

If you have Git installed, can you try this out:
```
pip install git+https://github.com/kylebarron/stata_kernel@dev-pygments --upgrade
```

Then when you do `jupyter notebook` and start a Stata kernel, it _should_ replace the Pygments code with our updated code. So for me, your code looks like this in an HTML file:
![image](https://user-images.githubusercontent.com/15164633/45527631-a841ad80-b7aa-11e8-8e02-be9c55510b31.png)

**Closed** 2018-09-14 04:33 UTC

**Comment by kylebarron** [comment] 2018-09-14 14:16
@jeremyfreese 

I ended up doing enough testing that I felt comfortable merging it. To get the upgrade, just do 
```
pip install stata_kernel --upgrade
```
as usual.
